import Image1 from "../src/assets/pro1.jpg"
import Image2 from "../src/assets/pro2.png"
import Image3 from "../src/assets/pro3.png"
import Image4 from "../src/assets/pro4.png"
import Image5 from "../src/assets/pro5.png"
import Image6 from "../src/assets/pro6.png"
import Image7 from "../src/assets/pro7.png"
import Image8 from "../src/assets/pro8.png"
import Image9 from "../src/assets/pro9.png"
import Image10 from "../src/assets/pro12.png"
import Image11 from "../src/assets/pro11.png"
import Image12 from "../src/assets/pro12.png"

let data = [
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 9,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 10,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image8,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 11,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image9,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 12,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image12,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image12,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image11,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image10,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image12,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image11,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image10,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
]

export default data